### PR TITLE
Added recordData variable

### PR DESCRIPTION
**Pull request by Avdbergnmf**
I needed something to disable data recording during some of the trials (familiarization trials). This seemed like the easiest way to accomplish that and figured others might be able to use it.

### CODE REVIEW

**Comment by jackbrookesfvr** [comment]
Thanks! I will review when I can.

But generally I am not convinced - why would you ever want to discard data even for familiarisation # trials? Is storage space an issue? You could mark them with a setting, then filter them out in data analysis.

**Comment by jackbrookes** [comment]
Thanks! I will review when I can.

But generally I am not convinced - why would you ever want to discard data even for familiarisation # trials? Is storage space an issue? You could mark them with a setting, then filter them out in data analysis.
________________________________

**Comment by Avdbergnmf** [comment]
Our experiment has a 5 min familiarization phase among some other stages (a training stage) that over ~30 participants will add up to a lot of additional data.
It's not going to be a huge problem, but a problem nonetheless. I like to clean up my data as early as possible.

**Comment by jackbrookes** [comment]
@Avdbergnmf what does the output look like when e.g. saving to csv (trial_results)? Are there blank rows?

**Comment by jackbrookes** [comment]
I added this feature but with a different method. The property is called `saveData` and can be assigned to a whole session, block or trial. Thanks!

**Pull request closed without merging**
